FROM python:3.13-slim

WORKDIR /app 

RUN apt-get update && apt-get install -y \ 
    build-essential \ 
    libpq-dev \
    curl \ 
    && rm -rf /var/lib/apt/lists/* 

COPY requirements.txt .

RUN pip install --upgrade pip 
RUN pip install --no-cache-dir -r requirements.txt 

COPY src/frontend ./frontend 

WORKDIR /app/frontend

CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
